const APP_NAME = 'AirBersih Backend';

const ROLES = {
  WARGA: 'WARGA',
  PENGURUS_RT_RW: 'PENGURUS_RT_RW',
  // Legacy/future roles: keep for SYNC-60 auth compatibility, not active MVP feature roles.
  ADMIN_SISTEM: 'ADMIN_SISTEM',
  MITRA_TUKANG: 'MITRA_TUKANG',
};

const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_MISSING: 'TOKEN_MISSING',
  TOKEN_INVALID: 'TOKEN_INVALID',
  FORBIDDEN: 'FORBIDDEN',
  USER_INACTIVE: 'USER_INACTIVE',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
};

module.exports = {
  APP_NAME,
  ROLES,
  ERROR_CODES,
};
