const APP_NAME = 'AirBersih Backend';

const ROLES = {
  WARGA: 'WARGA',
  PENGURUS_RT_RW: 'PENGURUS_RT_RW',
  // Legacy/future roles: keep for SYNC-60 auth compatibility, not active MVP feature roles.
  ADMIN_SISTEM: 'ADMIN_SISTEM',
  MITRA_TUKANG: 'MITRA_TUKANG',
};

const QUALITY_STATUS = {
  CLEAR: 'CLEAR',
  MILD_TURBID: 'MILD_TURBID',
  TURBID: 'TURBID',
  UNSAFE: 'UNSAFE',
};

const READING_SOURCE = {
  MQTT: 'MQTT',
  REST: 'REST',
};

const PUMP_STATUS = {
  ON: 'ON',
  OFF: 'OFF',
};

const PUMP_COMMAND = {
  ON: 'ON',
  OFF: 'OFF',
};

const PUMP_DEVICE_STATUS = {
  ON: 'ON',
  OFF: 'OFF',
  ERROR: 'ERROR',
  OFFLINE: 'OFFLINE',
};

const PUMP_LOG_SOURCE = {
  WEB: 'WEB',
  MQTT: 'MQTT',
  AUTO: 'AUTO',
  MANUAL: 'MANUAL',
  SYSTEM: 'SYSTEM',
};

const PUMP_COMMAND_SOURCE = {
  WEB: 'WEB',
};

const PUBLISH_STATUS = {
  SENT: 'SENT',
  FAILED: 'FAILED',
  SKIPPED: 'SKIPPED',
};

const TANK_RAW_STATUS = {
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  FULL: 'FULL',
};

const SOIL_STATUS = {
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
};

const MODEL_SOURCE = {
  DB: 'DB',
  MOCK: 'MOCK',
  ML_MODEL: 'ML_MODEL',
};

const MODEL_STATUS = {
  PENDING: 'PENDING',
  READY: 'READY',
};

const ALERT_TYPE = {
  WATER_QUALITY: 'WATER_QUALITY',
};

const ALERT_LEVEL = {
  WARNING: 'WARNING',
  DANGER: 'DANGER',
  CRITICAL: 'CRITICAL',
};

const ALERT_STATUS = {
  ACTIVE: 'ACTIVE',
  HANDLING: 'HANDLING',
  RESOLVED: 'RESOLVED',
};

const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_MISSING: 'TOKEN_MISSING',
  TOKEN_INVALID: 'TOKEN_INVALID',
  FORBIDDEN: 'FORBIDDEN',
  USER_INACTIVE: 'USER_INACTIVE',
  MQTT_NOT_READY: 'MQTT_NOT_READY',
  NOT_FOUND: 'NOT_FOUND',
  NODE_NOT_FOUND: 'NODE_NOT_FOUND',
  TANK_NOT_FOUND: 'TANK_NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
};

module.exports = {
  APP_NAME,
  ROLES,
  QUALITY_STATUS,
  READING_SOURCE,
  PUMP_STATUS,
  PUMP_COMMAND,
  PUMP_DEVICE_STATUS,
  PUMP_LOG_SOURCE,
  PUMP_COMMAND_SOURCE,
  PUBLISH_STATUS,
  TANK_RAW_STATUS,
  SOIL_STATUS,
  MODEL_SOURCE,
  MODEL_STATUS,
  ALERT_TYPE,
  ALERT_LEVEL,
  ALERT_STATUS,
  ERROR_CODES,
};
